name: Get modified Brands
description: "Check modified Brand folders to know brands to deploy"

runs:
  using: "composite"
  steps:
    # detect brand folders (with manifest.json inside)
    - name: Detect Brand folders
      id: get-brand-folders
      run: |
        ./scripts/get-brand-folders.sh > brand-folders.txt
      shell: bash  

    # get modified brand folders (based on brand-folders.txt file)  
    - name: Check changed folders
      id: changed-brand-folders
      uses: tj-actions/changed-files@v35
      with:
        files_from_source_file: brand-folders.txt  # Contains all brand subfolders
        dir_names: "true" # get only dir names and not all modified file names
        dir_names_max_depth: '1' # get only first dir path (root)

    # Export changed-brand-folders output
    - name: Set changed folders output
      id: changed-brand-output
      run: echo "changed_brands=${{ steps.changed-brand-folders.outputs.all_modified_files }}" >> $GITHUB_ENV
      shell: bash    