name: Sync Manifest Properties

on:
  pull_request:
    types: 
      - opened
      - edited
      - synchronize
    branches:
      - "*"
  workflow_dispatch:
    inputs:
      brand:
        type: choice
        description: "Choose the Brand"
        options:
          # integrate when a new brand is added/removed (with folder name)
          - hc_io
          - hc_send
          - hc_pagopa
          - hc_home
        required: true
      theme_id:
        description: "Theme ID to sync"
        required: true

jobs:
  export-theme:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@755da8c3cf115ac066823e79a1e1788f8940201b
        with:
          ref: ${{ github.ref_name }} # checkout to branch chosen when action was started

      # action runnable only on branches not equal to main
      - name: Check branch
        run: |
          if [ "${{ github.ref_name }}" == "main" ]; then
            echo "Error: you can't run Sync Manifest Properties action on main branch!"
            exit 1
          fi

      # call common node setup workflow
      - name: Node setup
        id: node-setup
        uses: ./.github/workflows/node-setup
        with:
          node-version-file: ".nvmrc"

      # call common set zendesk env variables workflow (for subdomain)
      - name: Set zendesk env variables for each brand
        id: zendesk-env
        uses: ./.github/workflows/set-zendesk-env-var
        with:
          # brands-folder: "${{ inputs.brand }}"
          brands-folder: hc_io
      
      # download zip theme
      - name: Download Theme
        env:
          API_BEARER_TOKEN: ${{ secrets.API_BEARER_TOKEN }}
        run: |
          # set/export zendesk env var to authentication 
          # export $(cat "${{ inputs.brand }}/.env" | xargs)
          export $(cat "hc_io/.env" | xargs)

          # run the download theme script 
          # node scripts/download-theme.js "${{ inputs.brand }}" "${{ inputs.theme_id }}"
          node scripts/download-theme.js hc_io 040395e5-f83a-438a-acd3-9a4d35e4a6f7

      # Replace manifest.json with the new one just downloaded (sync)
      - name: Replace manifest.json
        run: |
          unzip theme.zip -d theme-extracted
          # cp ./theme-extracted/manifest.json ./${{ inputs.brand }}/manifest.json
          cp ./theme-extracted/manifest.json ./hc_io/manifest.json
      
      # commit sync manifest
      - name: Commit changes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          # git add ${{ inputs.brand }}/manifest.json
          git add hc_io/manifest.json
          # git commit -m "chore(manifest.json): ${{ inputs.brand }} sync properties"
          git commit -m "chore(manifest.json): hc_io sync properties"
          git push origin ${{ github.ref_name }}